server:
  id: account-1
  httpPort: 8101

app:
  version: "1.0.0"
  web: ""
  priKey: game_secret_key

hall:
  ip: localhost
  port: 7100

redis:
  host: localhost
  port: 6379
  password: 

mybatis:
  url: jdbc:mysql://localhost:3306/game?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
  username: root
  password: 123456
  poolMaxSize: 10
