server:
  port: 8081

mybatis:
  url: jdbc:mysql://host.docker.internal:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: 123456
  poolMaxSize: 10

consul:
  host: consul
  port: 8500

service:
  name: user-service
  host: auto
  port: 8081
  healthCheckPath: /health
  healthCheckInterval: 10s
