server:
  port: 8080

jdbc:
  url: jdbc:mysql://localhost:3306/litejava?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: 123456

upload:
  dir: uploads
  maxSize: 10485760
