server:
  port: 8083

mybatis:
  url: jdbc:mysql://localhost:3306/product_db?useSSL=false&serverTimezone=UTC
  username: root
  password: 123456
  poolMaxSize: 10

consul:
  host: localhost
  port: 8500

service:
  name: product-service
  host: host.docker.internal
  port: 8083
  healthCheckPath: /health
  healthCheckInterval: 10s
