server:
  id: doudizhu-1
  wsPort: 9100
  httpPort: 9101
  advertiseHost: localhost
  advertiseWsPort: 9100
  advertiseHttpPort: 9101

game:
  type: doudizhu
  maxPlayers: 3

hall:
  url: http://localhost:8201
