server:
  port: 8086

mybatis:
  url: jdbc:mysql://localhost:3306/notification_db?useSSL=false&serverTimezone=UTC
  username: root
  password: 123456
  poolMaxSize: 10

consul:
  host: localhost
  port: 8500

service:
  name: notification-service
  host: host.docker.internal
  port: 8086
  healthCheckPath: /health
  healthCheckInterval: 10s
