server:
  port: 8085

mybatis:
  url: jdbc:mysql://host.docker.internal:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: 123456
  poolMaxSize: 10

consul:
  host: consul
  port: 8500

jwt:
  secret: litejava-jwt-secret-key-32chars!
  expireHours: 24

service:
  name: auth-service
  host: host.docker.internal
  port: 8085
  healthCheckPath: /health
  healthCheckInterval: 10s
