server:
  port: 8081

mybatis:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: 123456
  poolMaxSize: 10

consul:
  host: ${CONSUL_HOST:localhost}
  port: 8500

service:
  name: user-service
  host: host.docker.internal
  port: 8081
  healthCheckPath: /health
  healthCheckInterval: 10s
