server:
  port: 8084

mybatis:
  url: jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=UTC
  username: root
  password: 123456
  poolMaxSize: 10

consul:
  host: localhost
  port: 8500

service:
  name: payment-service
  host: host.docker.internal
  port: 8084
  healthCheckPath: /health
  healthCheckInterval: 10s
